using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleQuizApp
{
    public class User
    {
        // Primary key for the User entity. The 'DatabaseGenerated' attribute specifies that the Id is generated by the database.
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // Username property.
        [Required, MinLength(4), MaxLength(12)]
        public required string Username { get; set; }

        // Password property.
        [Required, MinLength(4), MaxLength(255)]
        public required string Password { get; set; }

        // A collection of quizzes associated with the user. This represents a one-to-many relationship.
        // A user can have multiple quizzes.
        public ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();
    }
}
